"""add_category_to_lineitem

Revision ID: 30d9b56f46dd
Revises: 21bae6a1715d
Create Date: 2026-05-23 18:10:29.007560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d9b56f46dd'
down_revision: Union[str, Sequence[str], None] = '21bae6a1715d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineitem', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineitem', 'category')
    # ### end Alembic commands ###
