"""add_confirmed_to_receipt

Revision ID: c51d314bd5dc
Revises: 41e9b56f46de
Create Date: 2026-06-09 14:21:37.948118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51d314bd5dc'
down_revision: Union[str, Sequence[str], None] = '41e9b56f46de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.execute("UPDATE receipt SET confirmed = FALSE")
    op.alter_column('receipt', 'confirmed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'confirmed')
    # ### end Alembic commands ###
